dataset: fashion-mnist

evolvingMode: On

numConvLayers: 3
numDenseLayers: 2

numEpochs: 2
batchSize: 32

numGenerations: 3
populationSize: 5
mutateProb: 0.2
sizeHallOfFame: 2
intelligentSurvival: Off

hyperparams:
  activation:   ["linear", "relu", "elu"]
  dropout:      [0.0, 0.05, 0.10, 0.15, 0.20]
  kernel_size:  [3, 5, 7]
  filters:      [8, 16, 32, 64]