dataset: fashion-mnist

numEpochs: 3
batchSize: 32

numGenerations: 3
populationSize: 50
mutateProb:       0.2

numConvLayers: 3
numDenseLayers: 2

hyperparams:
  activation:   ["linear", "relu", "elu"]
  dropout:      [0.0, 0.05, 0.10, 0.15, 0.20]
  kernel_size:  [3, 5, 7]
  filters:      [8, 16, 32, 64]