dataset: fashion-mnist

numEpochs: 2
batchSize: 32

numGenerations: 10
populationSize: 4
mutateProb: 0.2
sizeHallOfFame: 5

numConvLayers: 3
numDenseLayers: 2

hyperparams:
  activation:   ["linear", "relu", "elu"]
  dropout:      [0.0, 0.05, 0.10, 0.15, 0.20]
  kernel_size:  [3, 5, 7]
  filters:      [8, 16, 32, 64]